server:
  port: 8762
spring:
  application:
    name: service-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/auth?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: root
      password: 4456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect
        
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
    client:
      client-id: service-center
      client-secret: 123456
      access-token-uri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials,password
      scope: server
      
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10070/eureka
  
